version: '3.8'
services:
  laser_sim:
    build: .
    image: laser_challenge_ros2:latest
    network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/ros2_ws/src/laser_challenge_simulation
    stdin_open: true
    tty: true