mavros:
  mavros:
    ros__parameters:
      fcu_url: "udp://127.0.0.1:14550@14550"
      gcs_url: ""
      target_system_id: 1
      target_component_id: 1
      distance_sensor:
        rangefinder_down:
          id: 0
          frame_id: "base_link"
          orientation: 25 # PITCH_270
          field_of_view: 0.0
          send_tf: true
          sensor_position: {x: 0.0, y: 0.0, z: 0.0}